%% 1 ~ 9 서로  다른 세자리 수
%%같은 수 같은 자리 - 스트라이크
%%같은 수 다른 자리 - 볼
%%같은 수 x - 낫싱
%%컴퓨터 - 랜덤 세 자리 숫자 생성
%%사용자 - 세 자리 숫자 입력
%%게임 재시작/종료 구분
flowchart
    A1[랜덤 세자리 숫자 생성]
    A2[사용자 숫자 읽기]
    A3{정답 여부 판단_볼, 스트라이크, 낫싱}
    A4{정답인 경우 게임 재시작 여부 묻기}
    EXIT[종료]
    A1 --> A2 --> A3
    A3 -->|o| A4
    A3 -->|x| A2
    A4 -->|yes_1| A1
    A4 -->|no_2| EXIT
